### ISSUE TITLE
What's the difference between PINOperationQueue and NSOperationQueue ?

### ISSUE THREAD

**Issue by joehsieh** [pinterest/PINOperation#13]
Hi, @garrettmoon 
Recently, I want to understand the design of PINCache by reviewing the code.(Here is my rough note: https://goo.gl/VRIXZD)
I realize that PINCache use PINOperation to schedule the threads to access the cache, but I'm curious about the difference between PINOperationQueue and NSOperationQueue.

Is PINOperationQueue better than NSOperationQueue in some situations ?

**Comment by garrettmoon** [comment]
@joehsieh yeah, this was essentially developed because we were seeing NSOperationQueue showing up in profiling when there were huge numbers of requests.
