### ISSUE TITLE
Support serial queue

### ISSUE THREAD

**Issue by garrettmoon** [pinterest/PINOperation#2]
As I originally wrote PINOperationQueue, I couldn't think of a good reason to use it over a standard serial queue when you only want a max operation. Turns out there is a good reason, support for coalescing operations and canceling them. Support for priority seems dangerous: if a high priority task depended on a lower priority task it could cause a deadlock, so I would shy away from supporting priority.

**Comment by maicki** [comment]
@garrettmoon You think the PR from above is enough to close the issue?

**Comment by garrettmoon** [comment]
Yup.
